# Generated by Django 5.0.3 on 2024-03-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptid', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=10)),
                ('dloc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=10)),
                ('esal', models.IntegerField()),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewset.dept')),
            ],
        ),
    ]
