# Generated by Django 5.0.3 on 2024-03-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='deptid',
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
